[package]
name = "dotcfg"
version = "0.1.0"
edition = "2024"
description = "Flexible config management for Rust CLIs — your path, your format"
license = "MIT OR Apache-2.0"
keywords = ["config", "configuration", "cli", "toml", "json"]
authors = ["Spectra010s <spectra010s@gmail.com>"]
repository = "https://github.com/Spectra010s/dotcfg"
homepage = "https://github.com/Spectra010s/dotcfg"
categories = ["config"]

[features]
default = ["toml"]
toml = ["dep:toml"]
json = ["dep:serde_json"]

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8", optional = true }
serde_json = { version = "1", optional = true }
home = "0.5"
etcetera = "0.8"
thiserror = "2"
